[tool.pdm]

[project]
name = "pkg-core"
version = "0.1.0"
description = "Core utilities"
authors = [
    {name = "John Doe", email = "johndoe@example.org"},
]
dependencies = []
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

[project.optional-dependencies]
cli = ["click"]
http = ["urllib3"]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
